# Development override for hot reloading
# Usage: docker compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src:ro
      - ./frontend/public:/app/public:ro
      - ./frontend/package.json:/app/package.json:ro
      - ./frontend/vite.config.js:/app/vite.config.js:ro
    environment:
      - VITE_API_URL=${VITE_API_URL}
    command: npm run dev -- --host 0.0.0.0
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    command: go run main.go
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      UPLOADS_DIR: ${UPLOADS_DIR}
      CORS_ORIGINS: ${CORS_ORIGINS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      AI_MODEL_PROVIDER: ${AI_MODEL_PROVIDER}
      OPENAI_MODEL: ${OPENAI_MODEL}
      ANTHROPIC_MODEL: ${ANTHROPIC_MODEL}
      CGO_ENABLED: 0

  migration:
    # Use same migration service in dev mode
    volumes:
      - ./db/migrations:/flyway/sql